# "prior": # ordered list of priors
#                 [{
#                     "name" : "Gauss",
#                     "params" : [0., 1.]
#                 },
#                 {
#                     "name" : "Uniform",
#                     "params" : [0., 10.]
#                 }],

model1:
    distributions: ["gauss", "unif", "gauss"]
    params: 2

